export const ROUTE_CHANGED = 'router/ROUTE_CHANGED';

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const SET_OWNER = 'SET_OWNER';

export const UPDATE_LOTTERY_BALANCE = 'UPDATE_LOTTERY_BALANCE';

export const SET_LOTTERY_BALANCE = 'SET_LOTTERY_BALANCE';

export const UPDATE_ENTER_AMOUNT = 'UPDATE_ENTER_AMOUNT';

export const UPDATE_ENTER_LOADING = 'UPDATE_ENTER_LOADING';

export const SET_PLAYERS = 'SET_PLAYERS';

export const UPDATE_PICK_WINNER_LOADING = 'UPDATE_PICK_WINNER_LOADING';

export const UPDATE_PLAYERS = 'UPDATE_PLAYERS';

export const SET_CONTRACT_ADDRESS = 'SET_CONTRACT_ADDRESS';

export const SET_WINNER = 'SET_WINNER';

export const CLEAR_PLAYERS = 'CLEAR_PLAYERS';

export const CLEAR_LOTTERY_BALANCE = 'CLEAR_LOTTERY_BALANCE';

export const SET_WIN_AMOUNT = 'SET_WIN_AMOUNT';
